// ─── Types ────────────────────────────────────────────────────────────────────

export type Channel = "chat" | "sms" | "email" | "voice" | "whatsapp";
export type Priority = "Critical" | "High" | "Medium" | "Low";
export type QueueAssignmentStatus = "open" | "pending" | "escalated" | "resolved" | "parked";

export interface AiOverview {
  actions: string[];
  whyNeeded: string;
  nextSteps: string[];
}

export interface StaticAssignment {
  id: string;
  name: string;
  customerId: string;
  customerRecordId?: string;
  company: string;
  channel: Channel;
  priority: Priority;
  status: QueueAssignmentStatus;
  preview: string;
  waitTime: string;
  aiOverview: AiOverview;
}

// ─── Static assignments ───────────────────────────────────────────────────────

export const staticAssignments: StaticAssignment[] = [
  {
    id: "static-1",
    name: "Maria Chen",
    customerId: "CST-10482",
    customerRecordId: "emily",
    company: "Apex Financial Group",
    channel: "chat",
    priority: "High",
    status: "open",
    preview: "Payment processing failure on recurring transactions",
    waitTime: "4m",
    aiOverview: {
      actions: [
        "Reviewed the full chat thread and identified a recurring payment failure tied to an expired card token.",
        "Cross-referenced Maria's billing profile and confirmed the card on file expired two billing cycles ago.",
        "Checked if the failure triggered any automated retry logic — no retries were attempted due to hard decline.",
        "Prepared a card-update prompt and drafted a payment link for agent delivery.",
      ],
      whyNeeded:
        "Maria's recurring transactions will continue to fail until the card token is replaced. A human agent is needed to verify her identity, confirm the new card details, and manually trigger the missed payment to bring the account current.",
      nextSteps: [
        "Verify Maria's identity before making billing changes",
        "Confirm and update the new card details on the account",
        "Manually trigger the missed recurring payment",
        "Confirm the account is current and future transactions are enabled",
      ],
    },
  },
  {
    id: "static-2",
    name: "James Whitfield",
    customerId: "CST-10591",
    customerRecordId: "david",
    company: "Summit Healthcare Inc.",
    channel: "voice",
    priority: "Critical",
    status: "open",
    preview: "Enterprise license renewal dispute — pricing discrepancy",
    waitTime: "19m",
    aiOverview: {
      actions: [
        "Reviewed James's enterprise contract and identified a tier pricing change applied at last renewal.",
        "Cross-referenced the original quote with the invoiced amount — a $4,200 discrepancy was found.",
        "Checked account notes and confirmed a verbal pricing commitment was made by the previous account manager.",
        "Flagged the case for revenue operations review and prepared a dispute summary for the agent.",
      ],
      whyNeeded:
        "This dispute involves a contractual pricing commitment that requires management approval to honour. A human agent must review the account history, engage the commercial team, and negotiate a resolution before Summit Healthcare escalates further.",
      nextSteps: [
        "Review the original quote and the disputed invoice side-by-side",
        "Confirm the verbal pricing commitment with the previous account manager",
        "Engage the commercial team for management approval on any correction",
        "Negotiate a resolution with James and document the outcome",
      ],
    },
  },
  {
    id: "static-3",
    name: "Priya Sharma",
    customerId: "CST-10814",
    customerRecordId: "priya",
    company: "Priya Sharma (Personal)",
    channel: "email",
    priority: "High",
    status: "open",
    preview: "Account security alert — unauthorized login detected",
    waitTime: "1h 48m",
    aiOverview: {
      actions: [
        "Reviewed the security alert and confirmed an unrecognised login from a foreign IP address.",
        "Checked session history — the suspicious session accessed personal details but no transactions were made.",
        "Initiated a temporary account lock and triggered a password reset notification to Priya's verified email.",
        "Prepared an incident summary and recommended MFA enablement steps for the agent to walk Priya through.",
      ],
      whyNeeded:
        "Although the account has been locked, Priya needs a human agent to confirm her identity, review whether any data was accessed, and guide her through securing the account. Trust and reassurance are critical in this interaction.",
      nextSteps: [
        "Verify Priya's identity before discussing any account details",
        "Review the suspicious session and confirm what data was accessed",
        "Walk Priya through the password reset and account recovery steps",
        "Enable MFA and confirm the account is fully secured",
      ],
    },
  },
  {
    id: "static-4",
    name: "Robert Okafor",
    customerId: "CST-10363",
    customerRecordId: "jamal",
    company: "BlueLine Logistics",
    channel: "sms",
    priority: "Medium",
    status: "open",
    preview: "API integration errors after platform migration",
    waitTime: "2m",
    aiOverview: {
      actions: [
        "Reviewed Robert's SMS thread and identified API authentication errors starting immediately post-migration.",
        "Checked the developer portal — BlueLine's API keys were not re-issued after the platform version upgrade.",
        "Confirmed the error pattern matches a known breaking change introduced in API v3.1.",
        "Prepared a migration guide and new key generation steps for the agent to share.",
      ],
      whyNeeded:
        "Issuing new API credentials and verifying the integration is restored requires coordination with the developer team. A human agent is needed to walk Robert through the key rotation and confirm the endpoint configuration is updated correctly.",
      nextSteps: [
        "Issue new API credentials from the developer portal",
        "Share the migration guide and v3.1 breaking-change notes with Robert",
        "Walk Robert through updating the endpoint configuration",
        "Verify the integration is restored and confirm with the developer team",
      ],
    },
  },
  {
    id: "static-5",
    name: "Lisa Montenegro",
    customerId: "CST-11024",
    customerRecordId: "lauren",
    company: "Coastal Realty Partners",
    channel: "email",
    priority: "Medium",
    status: "pending",
    preview: "Bulk data export request — compliance deadline",
    waitTime: "49m",
    aiOverview: {
      actions: [
        "Reviewed Lisa's email thread and confirmed a GDPR-mandated data export was requested 18 days ago.",
        "Checked the data export queue — the request stalled due to a missing data-owner approval in the system.",
        "Identified the responsible internal team and flagged the overdue approval to compliance ops.",
        "Prepared an export status summary and escalation note for the agent.",
      ],
      whyNeeded:
        "Lisa's compliance deadline is imminent and the export request is overdue. A human agent must coordinate with the data team, force-approve the stalled request, and confirm delivery to Lisa with a compliance-safe confirmation email.",
      nextSteps: [
        "Coordinate with the data team to unblock the stalled approval",
        "Force-approve the export request in the compliance system",
        "Confirm delivery of the export to Lisa within the deadline",
        "Send a compliance-safe confirmation email and close the case",
      ],
    },
  },
  {
    id: "static-6",
    name: "Kevin Tran",
    customerId: "CST-11130",
    customerRecordId: "miguel",
    company: "Orion Pharma Group",
    channel: "voice",
    priority: "Critical",
    status: "pending",
    preview: "Billing system discrepancy causing double invoices",
    waitTime: "7m",
    aiOverview: {
      actions: [
        "Reviewed Kevin's billing history and confirmed duplicate invoices were generated for three consecutive months.",
        "Identified a billing system sync error introduced during last quarter's ERP migration as the root cause.",
        "Calculated the total overbilling: $12,600 across three invoices — all currently marked as overdue.",
        "Prepared a credit memo draft and flagged the case to the billing engineering team.",
      ],
      whyNeeded:
        "Kevin has already escalated this case once without resolution. A human agent must personally confirm the overbilling amount, issue the credits, and ensure the ERP sync is corrected to prevent future duplicates. Orion Pharma is a key account.",
      nextSteps: [
        "Confirm the total overbilling amount across all three invoices",
        "Issue the credit memos and update the account balance",
        "Escalate the ERP sync error to billing engineering for a permanent fix",
        "Personally confirm with Kevin that the credits have been applied",
      ],
    },
  },
  {
    id: "static-7",
    name: "Angela Russo",
    customerId: "CST-11247",
    customerRecordId: "hannah",
    company: "Clearwater Consulting",
    channel: "chat",
    priority: "Low",
    status: "pending",
    preview: "Request to update payment method on file",
    waitTime: "1h 12m",
    aiOverview: {
      actions: [
        "Reviewed Angela's chat and confirmed she is requesting a payment method update for her corporate account.",
        "Verified Angela's identity meets the account's security threshold for payment detail changes.",
        "Confirmed no active transactions are pending that would be affected by the card change.",
        "Prepared a secure payment update link and draft confirmation message for the agent.",
      ],
      whyNeeded:
        "Payment method updates on corporate accounts require agent verification and manual confirmation in the billing system. A human agent must validate Angela's authorisation level before making changes to the account on file.",
      nextSteps: [
        "Verify Angela's authorisation level for corporate account changes",
        "Confirm no active transactions will be affected by the card change",
        "Send the secure payment update link and assist Angela through the process",
        "Confirm the new payment method is active and send a confirmation",
      ],
    },
  },
  {
    id: "static-8",
    name: "Marcus Bell",
    customerId: "CST-11389",
    customerRecordId: "alex",
    company: "Vertex Systems",
    channel: "email",
    priority: "High",
    status: "open",
    preview: "SSO configuration broken after directory sync",
    waitTime: "33m",
    aiOverview: {
      actions: [
        "Reviewed Marcus's email thread and confirmed SSO broke immediately after an Azure AD directory sync.",
        "Checked Vertex's SSO configuration — the entity ID and assertion consumer URL are now mismatched.",
        "Confirmed the sync overwrote a custom attribute mapping that was set manually.",
        "Prepared a re-configuration guide and flagged the issue to the identity team.",
      ],
      whyNeeded:
        "Restoring SSO requires manual changes to both the identity provider settings and the application configuration. A human agent must coordinate with Vertex's IT admin and validate the corrected configuration before re-enabling access.",
      nextSteps: [
        "Coordinate with Vertex's IT admin to access the identity provider settings",
        "Apply the corrected entity ID and assertion consumer URL configuration",
        "Restore the custom attribute mapping that was overwritten by the sync",
        "Test SSO end-to-end and confirm access is restored for Vertex users",
      ],
    },
  },
  {
    id: "static-9",
    name: "Sandra Yip",
    customerId: "CST-11412",
    customerRecordId: "sarah",
    company: "Harbor Bridge Capital",
    channel: "sms",
    priority: "Medium",
    status: "open",
    preview: "Unable to access quarterly reports in portal",
    waitTime: "15m",
    aiOverview: {
      actions: [
        "Reviewed Sandra's SMS thread and confirmed she cannot access the Q1 and Q2 report documents in the portal.",
        "Checked her account permissions — the reports portal role was inadvertently removed during a user audit.",
        "Confirmed the reports are available and the issue is entirely permission-based, not a data problem.",
        "Prepared a permission restoration request and flagged it to the admin team.",
      ],
      whyNeeded:
        "Restoring portal access requires an admin-level permission change. A human agent must confirm Sandra's role entitlements, apply the correction, and verify she can access the required reports before closing the case.",
      nextSteps: [
        "Confirm Sandra's correct role entitlements for the reports portal",
        "Apply the permission restoration in the admin panel",
        "Verify Sandra can access the Q1 and Q2 report documents",
        "Close the case and confirm with Sandra that access is restored",
      ],
    },
  },
  {
    id: "static-10",
    name: "Derek Owens",
    customerId: "CST-11508",
    customerRecordId: "emily",
    company: "Stonewall Manufacturing",
    channel: "voice",
    priority: "High",
    status: "open",
    preview: "Contract renewal terms need urgent clarification",
    waitTime: "2h 3m",
    aiOverview: {
      actions: [
        "Reviewed Derek's account and identified his annual contract expires in 11 days with no renewal initiated.",
        "Cross-referenced the contract terms — a 30-day notice clause means renewal is technically overdue.",
        "Identified two pricing options available under the current commercial framework.",
        "Prepared a contract summary and renewal options brief for the agent.",
      ],
      whyNeeded:
        "Contract renewal negotiations require human judgement on pricing flexibility and relationship management. A human agent must engage Derek, clarify the terms, and secure a signed renewal before the contract lapses to avoid a service disruption.",
      nextSteps: [
        "Contact Derek urgently given the 11-day renewal window",
        "Review the available pricing options under the current framework",
        "Clarify contract terms and address any questions Derek has",
        "Secure a signed renewal before the contract lapses",
      ],
    },
  },
  {
    id: "static-11",
    name: "Fatima Al-Rashid",
    customerId: "CST-11621",
    customerRecordId: "david",
    company: "Crescent Media Group",
    channel: "chat",
    priority: "Critical",
    status: "pending",
    preview: "Data breach concern — suspicious export activity flagged",
    waitTime: "11m",
    aiOverview: {
      actions: [
        "Reviewed the security alert and confirmed an abnormal bulk data export was initiated from Fatima's account.",
        "Cross-referenced login timestamps — the export was triggered 40 minutes after an unrecognised session began.",
        "Suspended the export job and flagged the session for security team investigation.",
        "Prepared an incident report and escalation summary for the agent and security team.",
      ],
      whyNeeded:
        "This is a potential data breach requiring immediate human intervention. A security agent must assess the scope of the export, notify the data protection officer, and engage Fatima to determine whether account credentials have been compromised.",
      nextSteps: [
        "Assess the full scope of the abnormal data export",
        "Notify the data protection officer immediately",
        "Engage Fatima to determine if credentials have been compromised",
        "Initiate full incident response protocol and document findings",
      ],
    },
  },
  {
    id: "static-12",
    name: "Tom Hargrove",
    customerId: "CST-11734",
    customerRecordId: "priya",
    company: "GreenLeaf Retail",
    channel: "email",
    priority: "Low",
    status: "resolved",
    preview: "Follow-up on last month's refund — confirmation needed",
    waitTime: "3h 20m",
    aiOverview: {
      actions: [
        "Reviewed Tom's email and confirmed he is following up on a refund issued 22 days ago.",
        "Checked the refund status — the credit was processed but the bank return is still pending clearance.",
        "Confirmed the refund amount of $340 is within the expected processing window for Tom's bank.",
        "Prepared a refund status update and estimated clearance timeline for the agent to share.",
      ],
      whyNeeded:
        "Although the refund was processed correctly, Tom needs a human agent to communicate the status clearly and provide a confirmed timeline. A personal follow-up will prevent further escalation and close the loop on this case.",
      nextSteps: [
        "Confirm the refund of $340 was processed correctly",
        "Provide Tom with the estimated bank clearance timeline",
        "Send a personal follow-up message with the status details",
        "Close the case once Tom confirms receipt",
      ],
    },
  },
  {
    id: "static-13",
    name: "Nadia Petrov",
    customerId: "CST-11856",
    customerRecordId: "jamal",
    company: "Eurozone Trade Ltd.",
    channel: "sms",
    priority: "Medium",
    status: "pending",
    preview: "International wire transfer delay beyond SLA window",
    waitTime: "58m",
    aiOverview: {
      actions: [
        "Reviewed Nadia's SMS thread and confirmed her international wire transfer is 3 days past the SLA window.",
        "Checked with the correspondent bank — the transfer is held pending SWIFT compliance screening.",
        "Identified a flag on the beneficiary country code that triggered an automated compliance hold.",
        "Prepared a compliance hold explanation and escalation path for the agent.",
      ],
      whyNeeded:
        "Releasing a compliance-held wire transfer requires a human agent to liaise with the compliance team, review the beneficiary details, and submit a manual clearance request. Nadia needs a clear status update and a firm release timeline.",
      nextSteps: [
        "Liaise with the compliance team regarding the SWIFT hold",
        "Review and confirm the beneficiary country code and details",
        "Submit a manual clearance request on Nadia's behalf",
        "Provide Nadia with a firm release timeline and status update",
      ],
    },
  },
  {
    id: "static-14",
    name: "Carlos Mendez",
    customerId: "CST-11972",
    customerRecordId: "lauren",
    company: "SouthStar Energy",
    channel: "voice",
    priority: "High",
    status: "open",
    preview: "Service outage impacting production pipeline monitoring",
    waitTime: "26m",
    aiOverview: {
      actions: [
        "Reviewed Carlos's call notes and confirmed a real-time data feed outage affecting pipeline monitoring dashboards.",
        "Checked system status — the outage is caused by a broken WebSocket connection in the v4.2 API gateway.",
        "Confirmed the engineering team is aware and a fix is in progress, estimated resolution in 2 hours.",
        "Prepared an outage briefing and interim monitoring workaround for the agent to share.",
      ],
      whyNeeded:
        "Carlos's production monitoring is offline and the situation carries operational risk. A human agent must confirm the incident timeline, provide SouthStar Energy with a reliable ETA, and arrange direct engineering contact if the outage extends beyond the estimate.",
      nextSteps: [
        "Confirm the current incident timeline and engineering ETA with the team",
        "Share the interim monitoring workaround with Carlos immediately",
        "Provide SouthStar Energy a reliable restoration ETA",
        "Arrange direct engineering contact if the outage extends beyond 2 hours",
      ],
    },
  },
  {
    id: "static-15",
    name: "Ingrid Holmberg",
    customerId: "CST-12045",
    customerRecordId: "miguel",
    company: "Nordic Freight Solutions",
    channel: "email",
    priority: "Medium",
    status: "open",
    preview: "Customs documentation error on recent shipment",
    waitTime: "44m",
    aiOverview: {
      actions: [
        "Reviewed Ingrid's email and identified an HS code classification error on a recent shipment declaration.",
        "Cross-referenced the declared goods with the correct tariff schedule — the error affects duty calculations.",
        "Confirmed the shipment is currently held at customs pending a corrected declaration.",
        "Prepared a corrected HS code recommendation and amendment filing instructions for the agent.",
      ],
      whyNeeded:
        "Amending a customs declaration requires a human agent to coordinate with the freight broker and submit a formal correction. Ingrid needs clear guidance on the amendment process and confirmation the shipment will be released without penalty.",
      nextSteps: [
        "Coordinate with the freight broker on the corrected HS code",
        "Submit the amended customs declaration to the relevant authority",
        "Confirm the shipment has been cleared for release",
        "Guide Ingrid through the amendment process and confirm no penalty",
      ],
    },
  },
  {
    id: "static-16",
    name: "Darius Knox",
    customerId: "CST-12187",
    customerRecordId: "darius",
    company: "Pinnacle Wealth Advisors",
    channel: "chat",
    priority: "Critical",
    status: "open",
    preview: "I just realized I sent money to the wrong account — I need this fixed right away",
    waitTime: "3m",
    aiOverview: {
      actions: [
        "Reviewed Darius's chat and confirmed a $47,500 transfer was sent to an incorrect beneficiary account.",
        "Checked the transfer status — the transaction completed 8 minutes ago and has not yet been settled.",
        "Identified the receiving institution and initiated a recall request through the payments network.",
        "Flagged the case as a priority incident and prepared a reversal brief for the agent.",
      ],
      whyNeeded:
        "Reversing a completed transfer requires immediate human action and direct contact with the receiving bank. A human agent must authorise the recall, coordinate with the payments team, and keep Darius informed at every step until the funds are confirmed returned.",
      nextSteps: [
        "Authorise the transfer recall in the payments system immediately",
        "Contact the receiving institution to request the reversal",
        "Coordinate with the payments team to track the recall status",
        "Keep Darius informed at every step until funds are confirmed returned",
      ],
    },
  },
  {
    id: "static-17",
    name: "Yuki Tanaka",
    customerId: "CST-12301",
    customerRecordId: "emily",
    company: "Tanaka Innovations",
    channel: "chat",
    priority: "High",
    status: "open",
    preview: "Virtual agent unable to process my subscription upgrade",
    waitTime: "6m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — virtual agent failed to locate Yuki's account during the upgrade flow.",
        "Confirmed the account lookup is failing due to a mismatched email domain after a recent corporate rebrand.",
        "Identified the correct account record and confirmed the upgrade tier requested is available.",
        "Prepared a manual upgrade path for the agent to apply directly.",
      ],
      whyNeeded: "The account lookup failure is blocking the automated upgrade path. A human agent must apply the upgrade manually and update the email domain on the account to prevent recurrence.",
      nextSteps: [
        "Locate Yuki's account using the legacy email domain",
        "Apply the requested subscription upgrade manually",
        "Update the email domain on the account to the new one",
        "Confirm the upgrade is active and send Yuki a confirmation",
      ],
    },
  },
  {
    id: "static-18",
    name: "Amara Osei",
    customerId: "CST-12415",
    customerRecordId: "sarah",
    company: "Osei Capital Partners",
    channel: "sms",
    priority: "Medium",
    status: "open",
    preview: "Bot keeps looping on my account verification — need a human",
    waitTime: "11m",
    aiOverview: {
      actions: [
        "Reviewed the SMS thread — virtual agent verification loop triggered by an expired security question on file.",
        "Checked Amara's account — the security question was set 4 years ago and the answer hash no longer matches.",
        "Confirmed identity can be verified through an alternate KYC method available to agents.",
        "Prepared the alternate verification steps for the human agent to proceed.",
      ],
      whyNeeded: "The automated verification loop cannot be broken without resetting the security question. A human agent must verify Amara's identity through alternate means and reset the security credential.",
      nextSteps: [
        "Use the alternate KYC method to verify Amara's identity",
        "Reset the expired security question on the account",
        "Confirm the virtual agent verification flow works after the reset",
        "Close the case and confirm with Amara that access is restored",
      ],
    },
  },
  {
    id: "static-19",
    name: "Patrick O'Brien",
    customerId: "CST-12528",
    customerRecordId: "miguel",
    company: "O'Brien & Associates",
    channel: "chat",
    priority: "Low",
    status: "open",
    preview: "AI suggested the wrong product — need correct recommendation",
    waitTime: "22m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — virtual agent recommended an entry-level plan despite Patrick's enterprise usage profile.",
        "Checked account usage metrics — Patrick's current consumption exceeds the recommended plan by 340%.",
        "Identified the correct enterprise plan and confirmed it includes all features Patrick requires.",
        "Prepared a side-by-side plan comparison and upgrade notes for the agent.",
      ],
      whyNeeded: "Overriding an AI recommendation and manually switching a customer's plan requires agent authorization. A human agent must walk Patrick through the correct option and apply the change with his consent.",
      nextSteps: [
        "Present Patrick with the correct enterprise plan recommendation",
        "Confirm the plan includes all features Patrick currently uses",
        "Apply the plan change with Patrick's explicit consent",
        "Confirm the change is active and billing is updated accordingly",
      ],
    },
  },
  {
    id: "static-20",
    name: "Chloe Beaumont",
    customerId: "CST-12639",
    customerRecordId: "lauren",
    company: "Beaumont Legal Group",
    channel: "sms",
    priority: "High",
    status: "open",
    preview: "Virtual agent closed my case without resolving it",
    waitTime: "8m",
    aiOverview: {
      actions: [
        "Reviewed case history — virtual agent auto-closed the case after a 24-hour inactivity window during a public holiday.",
        "Confirmed the original issue (document upload failure) was never resolved at time of closure.",
        "Reopened the case and reviewed the document upload pipeline for any ongoing errors.",
        "Identified a file size limit misconfiguration affecting Chloe's account tier.",
      ],
      whyNeeded: "The auto-closure was a system error compounded by a misconfiguration. A human agent must acknowledge the error, resolve the document upload issue, and ensure Chloe's case is fully closed to her satisfaction.",
      nextSteps: [
        "Apologize for the premature case closure and acknowledge the error",
        "Fix the file size limit configuration on Chloe's account",
        "Assist Chloe in completing the document upload successfully",
        "Confirm the case is resolved and close it with Chloe's confirmation",
      ],
    },
  },
  {
    id: "static-21",
    name: "Rajiv Menon",
    customerId: "CST-12750",
    customerRecordId: "jamal",
    company: "Menon Tech Solutions",
    channel: "chat",
    priority: "Critical",
    status: "open",
    preview: "AI provided incorrect compliance guidance — urgent correction needed",
    waitTime: "2m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — virtual agent cited an outdated compliance regulation that was revised in Q3.",
        "Cross-referenced the correct current regulation and confirmed the guidance given was materially incorrect.",
        "Identified that Rajiv may have already acted on the incorrect guidance in a live filing.",
        "Prepared a corrected compliance summary and flagged the case as urgent.",
      ],
      whyNeeded: "Incorrect compliance guidance may have triggered an erroneous regulatory filing. A human agent with compliance expertise must correct the record, contact the relevant regulatory body if required, and document the incident.",
      nextSteps: [
        "Immediately correct the compliance guidance provided to Rajiv",
        "Determine if any action was taken based on the incorrect guidance",
        "Contact the regulatory body if a filing correction is needed",
        "Document the AI error and escalate to the compliance quality team",
      ],
    },
  },
  {
    id: "static-22",
    name: "Sophie Hartmann",
    customerId: "CST-12863",
    customerRecordId: "hannah",
    company: "Hartmann Logistics GmbH",
    channel: "sms",
    priority: "Medium",
    status: "open",
    preview: "Bot couldn't understand my shipment tracking query",
    waitTime: "17m",
    aiOverview: {
      actions: [
        "Reviewed SMS thread — virtual agent could not parse Sophie's tracking reference format from the partner carrier.",
        "Checked the tracking number against the partner carrier API — shipment is located and en route.",
        "Confirmed the virtual agent's carrier lookup table is missing the partner carrier's prefix.",
        "Prepared tracking details and expected delivery window for the agent to share.",
      ],
      whyNeeded: "The virtual agent's carrier table gap cannot be fixed in this session. A human agent must provide Sophie with the tracking information directly and log the gap for the product team to address.",
      nextSteps: [
        "Share the shipment tracking details and ETA with Sophie directly",
        "Confirm the delivery address and any special handling instructions",
        "Log the carrier lookup gap for the product team to fix",
        "Close the case once Sophie confirms the information is satisfactory",
      ],
    },
  },
  {
    id: "static-23",
    name: "Terrence Vance",
    customerId: "CST-12974",
    customerRecordId: "alex",
    company: "Vance Capital Management",
    channel: "chat",
    priority: "High",
    status: "open",
    preview: "Virtual agent gave wrong account balance — discrepancy of $18,000",
    waitTime: "5m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — virtual agent pulled balance from a cached snapshot 3 days out of date.",
        "Confirmed current live balance with the core banking system — $18,200 discrepancy vs. what was displayed.",
        "Identified a cache invalidation failure tied to a weekend batch job that did not complete.",
        "Prepared the correct balance and a brief explanation of the technical cause for the agent.",
      ],
      whyNeeded: "Providing incorrect financial information is a critical trust issue. A human agent must personally confirm the correct balance, explain the discrepancy clearly, and ensure Terrence has not made any decisions based on the incorrect figure.",
      nextSteps: [
        "Confirm the correct current balance with Terrence directly",
        "Explain the cache discrepancy clearly and reassure him",
        "Check if Terrence made any financial decisions based on the wrong balance",
        "Escalate the batch job failure to the engineering team for immediate fix",
      ],
    },
  },
  {
    id: "static-24",
    name: "Isabella Moreno",
    customerId: "CST-13085",
    customerRecordId: "priya",
    company: "Moreno & Partners Law",
    channel: "sms",
    priority: "Low",
    status: "open",
    preview: "Need to speak to a human — AI not helpful for my situation",
    waitTime: "31m",
    aiOverview: {
      actions: [
        "Reviewed SMS thread — virtual agent attempted standard triage but Isabella's issue involves a bespoke contract arrangement not in the knowledge base.",
        "Confirmed Isabella's account has a custom SLA agreement that requires manual handling.",
        "Checked account notes — a previous agent flagged this account for human-only contact preference.",
        "Prepared account context and custom SLA details for the human agent.",
      ],
      whyNeeded: "Isabella's account has a custom arrangement that falls outside automated handling. A human agent must review the bespoke contract terms and respond accordingly, respecting the account's human-contact preference.",
      nextSteps: [
        "Review Isabella's custom SLA agreement before engaging",
        "Address her issue within the terms of the bespoke contract",
        "Confirm the resolution aligns with her custom arrangement",
        "Note the interaction and update the account preference flag if needed",
      ],
    },
  },
  {
    id: "static-25",
    name: "David Park",
    customerId: "CST-13196",
    customerRecordId: "david",
    company: "Park Digital Agency",
    channel: "chat",
    priority: "Medium",
    status: "open",
    preview: "Virtual agent escalated my password reset — token not arriving",
    waitTime: "14m",
    aiOverview: {
      actions: [
        "Reviewed chat thread — virtual agent triggered a password reset but the token email has not arrived after 20 minutes.",
        "Checked the email delivery log — the message was soft-bounced by David's corporate spam gateway.",
        "Confirmed the reset token is valid and can be re-sent to an alternate verified contact method.",
        "Prepared an alternate delivery path for the agent to use.",
      ],
      whyNeeded: "The bounced token requires agent intervention to resend via an alternate method and confirm receipt. The agent must also whitelist the domain with the customer's IT team to prevent recurrence.",
      nextSteps: [
        "Resend the reset token to David's verified mobile number",
        "Confirm David receives and successfully uses the token",
        "Advise David's IT team to whitelist the sending domain",
        "Verify login is restored and close the case",
      ],
    },
  },
  {
    id: "static-26",
    name: "Aaliya Nasser",
    customerId: "CST-13307",
    customerRecordId: "sarah",
    company: "Nasser Trading Co.",
    channel: "sms",
    priority: "High",
    status: "open",
    preview: "Bot approved a transaction it should have flagged for review",
    waitTime: "9m",
    aiOverview: {
      actions: [
        "Reviewed the transaction — a $22,000 cross-border payment was auto-approved despite exceeding the manual review threshold.",
        "Checked the review threshold settings — a configuration change last week inadvertently raised the limit.",
        "Confirmed the payment has not yet been settled and is still within the recall window.",
        "Flagged the configuration error to compliance and prepared a recall brief for the agent.",
      ],
      whyNeeded: "This transaction requires immediate human review before it settles. A human agent must assess whether the payment should proceed or be recalled, and coordinate the configuration fix with the compliance team.",
      nextSteps: [
        "Review the $22,000 cross-border payment details immediately",
        "Determine whether to proceed or initiate a recall before settlement",
        "Coordinate the threshold configuration fix with the compliance team",
        "Document the incident and notify the relevant oversight team",
      ],
    },
  },
  {
    id: "static-27",
    name: "Finn Johansson",
    customerId: "CST-13418",
    customerRecordId: "miguel",
    company: "Johansson Nordic AB",
    channel: "chat",
    priority: "Low",
    status: "open",
    preview: "AI couldn't answer questions about my new plan features",
    waitTime: "27m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — Finn's questions relate to features released in the last product update, which are not yet in the virtual agent's knowledge base.",
        "Confirmed the features Finn is asking about are live and available on his plan tier.",
        "Located the correct feature documentation and usage guides.",
        "Prepared a feature summary and setup instructions for the agent to share.",
      ],
      whyNeeded: "The knowledge base gap means the virtual agent cannot answer Finn's questions accurately. A human agent must walk Finn through the new features and submit a knowledge base update request.",
      nextSteps: [
        "Walk Finn through the new features available on his plan",
        "Share the relevant documentation and setup guides",
        "Submit a request to update the virtual agent knowledge base",
        "Confirm Finn is satisfied and the features are working correctly",
      ],
    },
  },
  {
    id: "static-28",
    name: "Grace Kim",
    customerId: "CST-13529",
    customerRecordId: "emily",
    company: "Kim & Associates CPA",
    channel: "sms",
    priority: "Critical",
    status: "open",
    preview: "Urgent: Virtual agent locked my account during tax filing season",
    waitTime: "1m",
    aiOverview: {
      actions: [
        "Reviewed the account lock — virtual agent applied a precautionary lock after detecting an unusual login pattern during peak hours.",
        "Confirmed the login was Grace herself accessing the system from a new device during a client meeting.",
        "Verified Grace's identity meets all unlock criteria.",
        "Prepared an immediate unlock path for the agent and a device whitelist update.",
      ],
      whyNeeded: "The account lock is preventing Grace from accessing critical client data during an active tax filing. Immediate human intervention is required to unlock the account, whitelist the new device, and confirm full access is restored.",
      nextSteps: [
        "Unlock Grace's account immediately",
        "Whitelist Grace's new device on the account",
        "Confirm full access to all client data is restored",
        "Review the lock trigger logic to prevent false positives during peak usage",
      ],
    },
  },
  {
    id: "static-29",
    name: "Liam Foster",
    customerId: "CST-13640",
    customerRecordId: "alex",
    company: "Foster Engineering Ltd.",
    channel: "chat",
    priority: "Medium",
    status: "open",
    preview: "Bot couldn't process my bulk invoice submission",
    waitTime: "19m",
    aiOverview: {
      actions: [
        "Reviewed chat thread — virtual agent returned a validation error on Liam's bulk invoice file.",
        "Checked the file — the CSV contains a non-standard delimiter introduced by Liam's accounting software export.",
        "Confirmed the bulk submission portal accepts pipe-delimited format as an alternative.",
        "Prepared a conversion guide and a corrected file template for the agent to share.",
      ],
      whyNeeded: "The formatting issue requires a human agent to guide Liam through the file correction and manually trigger the submission once the corrected file is uploaded, as bulk retries require agent authorisation.",
      nextSteps: [
        "Share the pipe-delimited template and conversion guide with Liam",
        "Assist Liam in re-exporting the file in the correct format",
        "Trigger the bulk submission manually once the file is corrected",
        "Confirm all invoices are processed and the submission is complete",
      ],
    },
  },
  {
    id: "static-30",
    name: "Nadia Volkov",
    customerId: "CST-13751",
    customerRecordId: "hannah",
    company: "Volkov Asset Management",
    channel: "sms",
    priority: "High",
    status: "open",
    preview: "AI couldn't verify my identity — account changes are urgent",
    waitTime: "13m",
    aiOverview: {
      actions: [
        "Reviewed SMS thread — virtual agent identity check failed because Nadia's registered phone number changed after a SIM migration.",
        "Confirmed Nadia's identity can be verified through secondary KYC documentation.",
        "Identified the urgent account change she needs: updating the primary contact number and nominee details.",
        "Prepared the alternate verification flow and account update checklist for the agent.",
      ],
      whyNeeded: "Identity verification failure is blocking time-sensitive account updates. A human agent must complete alternate KYC verification and process the nominee and contact updates within the compliance window.",
      nextSteps: [
        "Complete alternate KYC verification using secondary documentation",
        "Update the primary contact number to Nadia's new SIM",
        "Process the nominee detail changes within the compliance window",
        "Confirm all changes are saved and send Nadia a confirmation",
      ],
    },
  },
  {
    id: "static-31",
    name: "Ethan Blake",
    customerId: "CST-13862",
    customerRecordId: "jamal",
    company: "Blake & Co. Investments",
    channel: "chat",
    priority: "Low",
    status: "open",
    preview: "Virtual agent sent me in circles — need someone to actually help",
    waitTime: "38m",
    aiOverview: {
      actions: [
        "Reviewed the chat transcript — Ethan's question about fee waivers triggered a loop between two virtual agent intents.",
        "Confirmed the loop is caused by a conflicting FAQ entry in the knowledge base.",
        "Identified that Ethan's account qualifies for a fee waiver under the loyalty program.",
        "Prepared a direct resolution path and the fee waiver application steps for the agent.",
      ],
      whyNeeded: "The virtual agent loop has frustrated Ethan and the resolution requires a human agent to apply the fee waiver directly and submit a knowledge base fix to resolve the conflicting intent.",
      nextSteps: [
        "Apologize for the circular experience and confirm a resolution is available",
        "Apply the fee waiver to Ethan's account under the loyalty program",
        "Submit a knowledge base fix for the conflicting FAQ entries",
        "Confirm the waiver is applied and close the case",
      ],
    },
  },
  {
    id: "static-32",
    name: "Mei Lin",
    customerId: "CST-13973",
    customerRecordId: "lauren",
    company: "Lin Pharmaceuticals",
    channel: "sms",
    priority: "High",
    status: "open",
    preview: "Automated agent gave incorrect dosage calculation guidance",
    waitTime: "4m",
    aiOverview: {
      actions: [
        "Reviewed SMS thread — virtual agent provided a calculation example using an outdated formula from an archived knowledge article.",
        "Confirmed the correct formula is documented in the current regulatory guidance.",
        "Identified the archived article is still indexed and accessible to the virtual agent — it should be retired.",
        "Prepared the correct guidance and flagged the article for immediate retirement.",
      ],
      whyNeeded: "Incorrect dosage guidance is a critical patient safety risk. A human agent must immediately correct the information provided and escalate the knowledge base error to the content and compliance teams.",
      nextSteps: [
        "Immediately correct the dosage calculation guidance provided to Mei",
        "Confirm Mei has the correct current formula and documentation",
        "Escalate the archived article for immediate retirement",
        "Notify the compliance and content teams of the knowledge base error",
      ],
    },
  },
  {
    id: "static-33",
    name: "Oliver Svensson",
    customerId: "CST-14084",
    customerRecordId: "david",
    company: "Svensson Group AB",
    channel: "chat",
    priority: "Medium",
    status: "open",
    preview: "Bot failed to book my appointment — double booking risk",
    waitTime: "21m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — virtual agent attempted to book a call-back slot but the calendar API returned a timeout error.",
        "Checked the calendar system — the timeout was caused by a sync delay during a maintenance window.",
        "Confirmed Oliver's preferred slot is still available.",
        "Prepared the booking details and a direct calendar link for the agent to complete manually.",
      ],
      whyNeeded: "The booking timeout left Oliver without a confirmed appointment, creating a double-booking risk if he retries independently. A human agent must complete the booking manually and confirm it directly with Oliver.",
      nextSteps: [
        "Confirm Oliver's preferred appointment slot is still available",
        "Book the appointment manually through the calendar system",
        "Send Oliver a confirmed appointment notification with details",
        "Monitor the calendar sync and confirm no double-booking occurred",
      ],
    },
  },
  {
    id: "static-34",
    name: "Priscilla Nakamura",
    customerId: "CST-14195",
    customerRecordId: "priya",
    company: "Nakamura Wealth Group",
    channel: "sms",
    priority: "Critical",
    status: "open",
    preview: "AI triggered an account freeze I didn't authorize",
    waitTime: "2m",
    aiOverview: {
      actions: [
        "Reviewed the account freeze — virtual agent misinterpreted an ambiguous customer message as a freeze request.",
        "Confirmed Priscilla did not authorize the freeze and is currently locked out of her investment account.",
        "Checked account activity — no suspicious transactions were detected that would justify the freeze.",
        "Prepared an immediate unfreeze authorization and incident log for the agent.",
      ],
      whyNeeded: "An unauthorized account freeze is blocking Priscilla's access to her investments. Immediate human intervention is required to reverse the freeze, restore full access, and file an incident report for the AI misinterpretation.",
      nextSteps: [
        "Immediately reverse the unauthorized account freeze",
        "Confirm Priscilla has full access to her investment account",
        "File an incident report for the AI misinterpretation",
        "Review and update the freeze intent logic to prevent recurrence",
      ],
    },
  },
  {
    id: "static-35",
    name: "Hugo Fernandez",
    customerId: "CST-14306",
    customerRecordId: "alex",
    company: "Fernandez Import-Export",
    channel: "chat",
    priority: "Low",
    status: "open",
    preview: "Virtual agent can't locate my order history from last year",
    waitTime: "44m",
    aiOverview: {
      actions: [
        "Reviewed chat thread — virtual agent query returned no results because Hugo's historic orders are in an archived data store not indexed by the current search.",
        "Located Hugo's order history in the legacy archive system.",
        "Confirmed the orders Hugo is looking for are present and intact.",
        "Prepared an export of the relevant order records for the agent to share.",
      ],
      whyNeeded: "Accessing archived data requires an agent with legacy system access. A human agent must retrieve the records, share them with Hugo, and submit a request to include legacy data in the search index.",
      nextSteps: [
        "Retrieve Hugo's order history from the legacy archive",
        "Share the relevant records with Hugo in a usable format",
        "Submit a request to include legacy data in the main search index",
        "Confirm Hugo has all the records he needs and close the case",
      ],
    },
  },
  {
    id: "static-36",
    name: "Thandi Mokoena",
    customerId: "CST-14417",
    customerRecordId: "sarah",
    company: "Mokoena Mining Corp",
    channel: "sms",
    priority: "High",
    status: "open",
    preview: "Bot can't process my VAT exemption certificate",
    waitTime: "16m",
    aiOverview: {
      actions: [
        "Reviewed SMS thread — virtual agent rejected Thandi's VAT exemption certificate due to an unrecognised issuing authority code.",
        "Confirmed the certificate is valid and issued by the correct authority for Thandi's jurisdiction.",
        "Identified that the authority code was added to the approved list only last month and the virtual agent's database hasn't been updated.",
        "Prepared a manual VAT exemption override path and the correct account update for the agent.",
      ],
      whyNeeded: "The outdated authority code database is blocking a valid exemption. A human agent must apply the VAT exemption manually and escalate the database update to the product team.",
      nextSteps: [
        "Manually verify and apply the VAT exemption on Thandi's account",
        "Confirm the exemption is reflected on future invoices",
        "Escalate the authority code database update to the product team",
        "Close the case and confirm with Thandi that billing is corrected",
      ],
    },
  },
  {
    id: "static-37",
    name: "Jerome Dupont",
    customerId: "CST-14528",
    customerRecordId: "miguel",
    company: "Dupont Financial Services",
    channel: "chat",
    priority: "Medium",
    status: "open",
    preview: "AI couldn't process my multi-currency transfer request",
    waitTime: "25m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — virtual agent declined the multi-currency transfer due to an unsupported currency pair in the automated flow.",
        "Confirmed the currency pair (EUR to SAR) is supported by the underlying payments network but not yet exposed in the virtual agent workflow.",
        "Checked Jerome's account — he has the required permissions for the transfer.",
        "Prepared the manual transfer initiation steps for the agent.",
      ],
      whyNeeded: "The currency pair gap in the virtual agent requires a human agent to initiate the transfer manually through the back-office payments system. Jerome needs the transfer completed today within the FX window.",
      nextSteps: [
        "Confirm the EUR to SAR transfer details with Jerome",
        "Initiate the transfer manually through the back-office system",
        "Confirm the FX rate applied and get Jerome's approval before executing",
        "Monitor the transfer and confirm completion with Jerome",
      ],
    },
  },
  {
    id: "static-38",
    name: "Vera Sokolova",
    customerId: "CST-14639",
    customerRecordId: "hannah",
    company: "Sokolova Group Holdings",
    channel: "sms",
    priority: "Low",
    status: "open",
    preview: "Virtual agent closed my chat before I finished explaining",
    waitTime: "52m",
    aiOverview: {
      actions: [
        "Reviewed SMS thread — virtual agent auto-closed the session after a 5-minute inactivity timeout while Vera was gathering documents.",
        "Confirmed Vera's underlying request (updating beneficiary details) was not started before the session closed.",
        "Checked account — no changes were made; the account is in the same state as before the session.",
        "Prepared the beneficiary update workflow for the agent to complete with Vera.",
      ],
      whyNeeded: "The premature session close frustrated Vera and she needs a human agent to complete the beneficiary update she originally requested. The agent should also review the inactivity timeout setting for this account type.",
      nextSteps: [
        "Acknowledge the session timeout issue and apologize to Vera",
        "Complete the beneficiary detail update Vera originally requested",
        "Confirm the update is saved and reflected correctly",
        "Review the inactivity timeout for this account type and escalate if too short",
      ],
    },
  },
  {
    id: "static-39",
    name: "Nathan Kowalski",
    customerId: "CST-14750",
    customerRecordId: "alex",
    company: "Kowalski Industrial",
    channel: "chat",
    priority: "High",
    status: "open",
    preview: "AI gave conflicting answers about my warranty claim eligibility",
    waitTime: "10m",
    aiOverview: {
      actions: [
        "Reviewed chat transcript — virtual agent gave two conflicting eligibility answers across separate sessions due to a knowledge base versioning conflict.",
        "Identified the conflict: one article reflects the old 12-month warranty policy; another reflects the new 24-month policy effective last quarter.",
        "Confirmed Nathan's purchase date qualifies under the new 24-month policy.",
        "Prepared a clear eligibility confirmation and claim initiation steps for the agent.",
      ],
      whyNeeded: "The conflicting guidance has created uncertainty and potential distrust. A human agent must confirm the correct policy, initiate the warranty claim on Nathan's behalf, and flag the knowledge base conflict for resolution.",
      nextSteps: [
        "Confirm Nathan is eligible under the 24-month warranty policy",
        "Initiate the warranty claim on Nathan's behalf",
        "Flag the conflicting knowledge base articles for immediate resolution",
        "Keep Nathan informed of the claim progress and expected timeline",
      ],
    },
  },
  {
    id: "static-40",
    name: "Aisha Kamara",
    customerId: "CST-14861",
    customerRecordId: "sarah",
    company: "Kamara Ventures",
    channel: "sms",
    priority: "Critical",
    status: "open",
    preview: "Bot sent my sensitive documents to the wrong recipient",
    waitTime: "1m",
    aiOverview: {
      actions: [
        "Reviewed the incident — virtual agent sent a document package to an incorrect email address due to a cached recipient from a previous session.",
        "Confirmed the documents contain personally identifiable financial information.",
        "Identified the incorrect recipient and initiated a recall request to the email provider.",
        "Flagged as a data incident and prepared an urgent notification for the DPO.",
      ],
      whyNeeded: "This is an active data breach incident. A human agent must coordinate with the DPO, initiate the formal incident response process, and notify Aisha of the breach in accordance with data protection obligations.",
      nextSteps: [
        "Notify the Data Protection Officer immediately",
        "Initiate the formal data incident response protocol",
        "Inform Aisha of the incident and the steps being taken",
        "Pursue the document recall and document all actions taken",
      ],
    },
  },
];
